### ISSUE TITLE
latest Update has crashed my site

### ISSUE THREAD

**Issue by spoddy** [ArthurGareginyan/best-preloader#1]
Warning: Constants may only evaluate to scalar values in /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php on line 69

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/wp-live-statistics/includes/wpls-functions.php on line 286

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-login.php on line 394

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-login.php on line 407

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/jetpack/modules/sso.php on line 641

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-includes/pluggable.php on line 904

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-includes/pluggable.php on line 905

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-includes/pluggable.php on line 906

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/n/n0n.co.uk/public_html/wp-content/plugins/best-preloader/best-preloader.php:69) in /var/sites/n/n0n.co.uk/public_html/wp-includes/pluggable.php on line 1195

**Comment by ArthurGareginyan** [comment]
I already released an update of the plugin (v4.1.1) with fixing the error. Please update plugin to the latest version. Sorry for the inconvenience.

**Comment by spoddy** [comment]
I can't get into my site at the moment and I don't understand why. I basically can't login to the wordpress admin area. Im trying it through FTP and can't connect that way either, and i do not know if this issue is being caused by your plugin.

I keep getting ERROR: Cookies are blocked due to unexpected output.

**Comment by ArthurGareginyan** [comment]
It's very strange. FTP access should work independently of any plugin, because it has nothing to do with plugins.

I can see the login form of your website at http://n0n.co.uk/wp-login.php. It's doesn't work?

**Comment by spoddy** [comment]
No it doesn't work.


________________________________

**Comment by ArthurGareginyan** [comment]
How about a hosting control panel (CPanel or another)? Do you have access to it?

**Comment by spoddy** [comment]
Normally yes, but the browser can't connect now for some reason.


________________________________

**Comment by ArthurGareginyan** [comment]
It's strange. I think you need to contact the hosting support and ask them to recover the access to hosting control panel and FTP of your website.

**Comment by spoddy** [comment]
I agree. I already have actually. Waiting. I will let you know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ArthurGareginyan** [comment]
OK. And again sorry for the inconvenience.

**Comment by ArthurGareginyan** [comment]
Done, I found the reason for this error. The problem is that an old version (v5.4 or v5.6) of PHP is installed on your website hosting. So now you have the two following variants:

1) Ask the support of your website hosting to upgrade the PHP (in your website environment) to version 7.0 or newer. And then this errors will disappear automatically.

2) In any way, update the plugin to the latest version (v4.1.1). This latest version is compatible with the old versions of PHP.

**Comment by spoddy** [comment]
Ahhh ok. Thanks for letting me know. Although why i have no access to cPanel or FTP is weird. Ill talk with my hoster. Thanks again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
